markdown: rdiscount
highlighter: true
permalink: /:year/:month/:day/:title.html
name: "Tom 的Blog"
markdown: rdiscount

author: "sunjianliang"
atom-baseurl: "http://tomsun.info"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

